server:
  port: 8082
spring:
  application:
    name: flow-eda-logger
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
security:
  oauth2:
    resource-id: flow-eda
    client-id: 1df7b0c1-aac0-148a14c7cba8
    client-secret: zcUaT32GlwIjz4yBJjYZIIMvzf
    check-token-url: http://localhost:8086/oauth/check_token
