server:
  port: 8086
spring:
  application:
    name: flow-eda-oauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flow_eda_oauth2?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
mybatis:
  configuration:
    map-underscore-to-camel-case: true
flow:
  oauth2:
    jwt_signing_key: flow-eda
    client_id: 1df7b0c1-aac0-148a14c7cba8
    client_secret: zcUaT32GlwIjz4yBJjYZIIMvzf
    authorities: ROLE_API,ROLE_WS
logging:
  level:
    org.springframework.security.oauth2.provider.token.store.JdbcTokenStore: warn
